---
  detectors:
    IrresponsibleModule:
      enabled: false
    TooManyStatements:
      exclude:
        - SECond::Edgar::FilingMapper#load_several
        - SECond::Edgar::EdgarApi#download_submission_url
        - SECond::Edgar::EdgarApi#submission_data
        - SECond::Service::AddFirm#store_firm
    UtilityFunction:
      enabled: false
    MissingSafeMethod:
      exclude:
        - SECond::FirmFiling
        - SECond::Submission::LocalFirmSubmissions
    Attribute:
      exclude:
        - SECond::Representer::OpenStructWithLinks#links
    FeatureEnvy:
      exclude:
        - SECond::Service::ListFirms#validate_list
        - SECond::Service::InspectFirm#calculate_readability
        - SECond::Service::AddFirm#format_cik
    UncommunicativeVariableName:
      exclude:
        - SECond::Service::AddFirm#find_firm
        - SECond::Service::AddFirm#store_firm
    RepeatedConditional:
      exclude:
        - SECond::App

  exclude_paths:
    - _snippets
    - spec/fixtures/firm_info.rb # one-time test fixture creator
    - app/infrastructure/edgar/10Kstore

  directories:
    "app/infrastructure/edgar":
      NestedIterators:
        enabled: false
      UtilityFunction:
        enabled: false

    "app/domain/firms/mappers":
      NestedIterators:
        enabled: false
